# Generated by Django 4.2.7 on 2023-11-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_of_use', models.FileField(upload_to='pdf_files/', verbose_name='Termos de uso')),
                ('privacy_policies', models.FileField(upload_to='pdf_files/', verbose_name='Políticas de privacidade')),
            ],
        ),
    ]
